INSERT INTO PRODUCERS(PRODUCER_ID, NAME, PRODUCER_URL, TOR, LAST_UPDATE, VERSION)
            VALUES (0, 'Apple', 'apple url', SYSDATE, SYSDATE, 0);
INSERT INTO PRODUCT(PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
            VALUES (0, 'Mac', 10, SYSDATE, 'product url', 0, 0);