INSERT INTO PRODUCERS(PRODUCER_ID, NAME, PRODUCER_URL, TOR, LAST_UPDATE, VERSION)
        VALUES (0, 'Apple', 'www.apple.com', SYSDATE, SYSDATE, 0);
INSERT INTO PRODUCERS(PRODUCER_ID, NAME, PRODUCER_URL, TOR, LAST_UPDATE, VERSION)
        VALUES (1, 'Samsung', 'www.samsung.com', SYSDATE, SYSDATE, 0);

INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iPhone SE', 549, SYSDATE, 'http://www.apple.com/iphone', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iPhone 6s', 669, SYSDATE, 'http://www.apple.com/iphone', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iPhone 7', 999, SYSDATE, 'http://www.apple.com/iphone', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iPhone 7 Plus', 1139, SYSDATE, 'http://www.apple.com/iphone', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iMac 21.5', 1299, SYSDATE, 'http://www.apple.com/mac/', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iMac 27', 2999, SYSDATE, 'http://www.apple.com/mac/', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'iPad Pro', 849, SYSDATE, 'http://www.apple.com/ipad/', 0, 0);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Watch 2', 475.56, SYSDATE, 'http://www.apple.com/watch/', 0, 0);

INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Galaxy S7', 546.42, SYSDATE, 'http://www.samsung.com/lv/smartphones/galaxy-s7', 0, 1);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Galaxy S7 Edge', 631.20, SYSDATE, 'http://www.samsung.com/lv/smartphones/galaxy-s7', 0, 1);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Galaxy Tab S2', 336, SYSDATE, 'http://www.samsung.com/lv/tablets', 0, 1);
INSERT INTO PRODUCT( PRODUCT_ID, NAME, PRICE, LAST_UPDATE, PRODUCT_URL, VERSION, PRODUCER_ID)
        VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Gear S3 Frontier', 399, SYSDATE, 'http://www.samsung.com/lv/wearables/gear', 0, 1);